build: set `esModuleInterop` to `true` to fix `@commitlint/types` import
This issue appeared after lock file maintenance, and is visible when building after recreating `package-lock.json`.

```
node_modules/@commitlint/types/lib/format.d.ts:1:8 - error TS1259: Module '"/home/jdebruijn/projects/commitlint-plugin-function-rules/node_modules/chalk/index"' can only be default-imported using the 'esModuleInterop' flag

1 import chalk from 'chalk';
         ~~~~~

  node_modules/chalk/index.d.ts:415:1
    415 export = chalk;
        ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

Found 1 error.
```